#! /usr/bin/python3
from PySide2.QtWidgets import QApplication
from PySide2.QtQuick import QQuickView
from PySide2.QtCore import QUrl, QObject, Slot, Signal,Property
import os
import subprocess
import sys

class Tunnel(QObject):

	def __init__(self):

		QObject.__init__(self)
		self._standAlone=False
		self.isStandAlone()

	#def __init	

	def isStandAlone(self):

		cmd='lliurex-version -v'
		p=subprocess.Popen(cmd,shell=True,stdout=subprocess.PIPE)
		result=p.communicate()[0]

		if type(result) is bytes:
			result=result.decode()
		flavours = [ x.strip() for x in result.split(',') ]

		for item in flavours:
			if 'server' in item:
				self.standAlone=False
				break
			elif 'client' in item:
				self.standAlone=False
				break
			elif 'desktop' in item:
				self.standAlone=True

		self.standAlone=False
	#def is_StandAlone

	def _getStandAlone(self):

		return self._standAlone

	#def _getLoadState	


	def _setStandAlone(self,standAlone):

		self._standAlone=standAlone
		self.on_standAlone.emit()

	#def _setLoadState
		
	on_standAlone=Signal()
	standAlone=Property(bool,_getStandAlone,_setStandAlone, notify=on_standAlone)

	@Slot(str)
	def on_ticket(self, ticket):
		
		ticket=ticket.replace(' ','##U+0020##')
		os.system("/usr/sbin/bell-scheduler-gui %s 2>/dev/null &"%ticket)
		app.quit()

app = QApplication([])
tunnel = Tunnel()
view = QQuickView()
view.rootContext().setContextProperty("tunnel", tunnel)
url = QUrl("/usr/lib/python3/dist-packages/bellscheduler/rsrc/login.qml")
view.setSource(url)
view.show()

sys.exit(app.exec_())