#!/usr/bin/python3

from PySide2.QtWidgets import QApplication
from PySide2.QtCore import QUrl
from PySide2.QtGui import QIcon
from PySide2.QtQml import QQmlApplicationEngine

import sys
from bellscheduler.Core import Core
c=Core.get_core()

app = QApplication()
engine = QQmlApplicationEngine()
engine.clearComponentCache()
context=engine.rootContext()
mainStackBridge=c.mainStack
bellStackBridge=c.bellStack
context.setContextProperty("mainStackBridge", mainStackBridge)
context.setContextProperty("bellStackBridge", bellStackBridge)

url = QUrl("/usr/lib/python3/dist-packages/bellscheduler/rsrc/bell-scheduler.qml")

engine.load(url)
if not engine.rootObjects():
	sys.exit(-1)

engine.quit.connect(QApplication.quit)
app.setWindowIcon(QIcon("/usr/share/icons/hicolor/scalable/apps/bell-scheduler.svg"));
ret=app.exec_()
del engine
del app
sys.exit(ret)

