#!/usr/bin/python3

from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QUrl
from PySide6.QtGui import QIcon
from PySide6.QtQml import QQmlApplicationEngine

import sys
from bellscheduler.Core import Core
c=Core.get_core()

app = QApplication()
app.setDesktopFileName("bell-scheduler")
engine = QQmlApplicationEngine()
engine.clearComponentCache()
context=engine.rootContext()
mainStackBridge=c.mainStack
bellsOptionsStackBridge=c.bellsOptionsStack
bellStackBridge=c.bellStack
holidayStackBridge=c.holidayStack
context.setContextProperty("mainStackBridge", mainStackBridge)
context.setContextProperty("bellsOptionsStackBridge", bellsOptionsStackBridge)
context.setContextProperty("bellStackBridge", bellStackBridge)
context.setContextProperty("holidayStackBridge",holidayStackBridge)

url = QUrl("/usr/lib/python3/dist-packages/bellscheduler/rsrc/bell-scheduler.qml")

engine.load(url)
if not engine.rootObjects():
	sys.exit(-1)

engine.quit.connect(QApplication.quit)
ret=app.exec()
del engine
del app
sys.exit(ret)

