Name=bell-scheduler
Name[en]=Bell Scheduler
Name[es]=Bell Scheduler
Name[ca_ES.UTF-8@valencia]=Bell Scheduler
Name[ca_ES@valencia]=Bell Scheduler
Name[ca@valencia]=Bell Scheduler
Comment=Application to program the alarms of the educational centers for the entrance, exit, recreation
Comment[es]=Aplicación para programar las alarmas de los centros educativos para la entrada, salida, recreo
Comment[ca_ES@valencia]=Aplicació per a programar les alarmes dels centres educatius per a l'entrada, eixida, recreo
Comment[ca_ES.UTF-8@valencia]=Aplicació per a programar les alarmes dels centres educatius per a l'entrada, eixida, recreo
Comment[ca@valencia]=Aplicació per a programar les alarmes dels centres educatius per a l'entrada, eixida, recreo
Icon=bell-scheduler
Category=Software
ScriptPath=bell-scheduler.zmd
Replaces=bell-scheduler-installer
Groups=sudo;admins;teachers
